In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent= [
    'the glass of milk', 
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meeaning of words',
    'your videos are good'
]

In [4]:
# Define the vocabulary size 

voc_size= 10000

In [5]:
# One hot Representation 

one_hot_repr= [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[1844, 4676, 3804, 7861],
 [1844, 4676, 3804, 7296],
 [1844, 1716, 3804, 2748],
 [717, 3500, 3311, 4212, 7252],
 [717, 3500, 3311, 4212, 4269],
 [4662, 1844, 2750, 3804, 7762],
 [4139, 9783, 1670, 4212]]

In [7]:
# Word Embedding representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length= 8 
embedded_docs= pad_sequences(one_hot_repr, padding= 'pre', maxlen= sent_length)
print(embedded_docs)


[[   0    0    0    0 1844 4676 3804 7861]
 [   0    0    0    0 1844 4676 3804 7296]
 [   0    0    0    0 1844 1716 3804 2748]
 [   0    0    0  717 3500 3311 4212 7252]
 [   0    0    0  717 3500 3311 4212 4269]
 [   0    0    0 4662 1844 2750 3804 7762]
 [   0    0    0    0 4139 9783 1670 4212]]


In [10]:
# feature representation 

dim= 10

In [18]:
model= Sequential()
model.add(Embedding(voc_size, dim, input_shape= (sent_length, )))
model.compile('adam', 'mse')

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


(7, 8, 10)

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 1844, 4676, 3804, 7861], dtype=int32)

In [24]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[-0.04399766,  0.01229057, -0.03269497, -0.03118144,  0.01087939,
        -0.02804658, -0.0371927 , -0.0418736 , -0.03949482, -0.01058839],
       [-0.04399766,  0.01229057, -0.03269497, -0.03118144,  0.01087939,
        -0.02804658, -0.0371927 , -0.0418736 , -0.03949482, -0.01058839],
       [-0.04399766,  0.01229057, -0.03269497, -0.03118144,  0.01087939,
        -0.02804658, -0.0371927 , -0.0418736 , -0.03949482, -0.01058839],
       [-0.04399766,  0.01229057, -0.03269497, -0.03118144,  0.01087939,
        -0.02804658, -0.0371927 , -0.0418736 , -0.03949482, -0.01058839],
       [ 0.01173295, -0.029727  ,  0.04392613,  0.0427973 ,  0.04843943,
         0.00650294, -0.03898951, -0.01150057, -0.00632459,  0.00990369],
       [ 0.00721688,  0.0453268 , -0.02357929, -0.00388074,  0.03856977,
         0.00549089,  0.03137701,  0.0029528 , -0.02879086,  0.01521336],
       [ 0.03159833,  0.03367822, -0.0244913 ,  0.03908755,  0.00036805,
         0.00829222,  0.04629408, -0.04467337